spring:
 profiles:
  active:
    - dev
---
spring:
 profiles: dev #开发环境
 application:
    name:microservicecloud-config-hang-dev

---
spring:
 profiles: test #开发环境
 application:
    name:microservicecloud-config-hang-test  
    
    
    